### ISSUE TITLE
Bug: no work!

### ISSUE THREAD

**Issue by Stretto** [rejectedsoftware/vibedist#3]
Yes, a bug! is this not maintained anymore? Could some documentation be written/added on how to use this?

**Comment by Stretto** [comment]
Error: no property 'renderCompat' for type 'vibe.http.server.HTTPServerResponse'

**Comment by s-ludwig** [comment]
Development is temporarily suspended, but will continue when some other projects get in a finished (v1) state. I'll put up a big notice in README.md.
